Back/mod seperate
3DPong/transcendence pull request #125
Opened 2023-04-11 12:45 UTC by csstring

# 목적
game mod분리, setinterval 내부에서 throw시 문제 발생, game Start api수정
## 구현 사항
  - [x] orginal pong game mod와 스킬, 장애물 등이 추가된 game mod에 대한 분리 
  - [x] setinterval 내부에서 throw execption을 하면 서버가 뻗는 문제가 발생하는 것으로 보임 테스트 후 코드 수정
  - [x] 지금은 game이 매칭 되면 바로 시작 되는데 화면 조정 할 시간이 필요해서 api를 수정해야함

2023-04-12 13:00 UTC, JuneParkCode requested changes
확인했고 Logger 쪽 수정사항이랑, 일부 질문 남겼습니다.

2023-04-13 03:28 UTC, csstring commented on backend/src/models/game/simul/GameManager.ts
> +        await gameService.createMatch(gameManager).then(()=>{
게임에 대한 정보를 서버 쪽에서 다 가지고  있다보니, database save 에러가 났을 때 클라이언트 한테 알려줘도 클라이언트가 할수 있는게 아무 것도 없어서 어차피 log기록 남겨놓고 게임결과 정합성만 유지 시키면 되지 않을까 하는 생각입니다...

2023-04-13 03:31 UTC, csstring commented on backend/src/models/game/simul/GameManager.ts
> +    this.logger = new Logger();
의견 반영 했습니다

2023-04-13 05:37 UTC, JuneParkCode approved these changes
확인했습니다

2023-04-13 05:42 UTC, kyu-baek commented on backend/src/models/game/socket/game.gateway.ts
> +  }
start 이벤트가 요청되고 이 if 조건식 false 가 하나라도 나오는 상황이면, gameStart가 되지 않을텐데, 그 경우에는 에러를 내보내지는 않나요?
대기하고 있으면 프론트에서 다시 start를 요청하게 되나요?

2023-04-13 05:45 UTC, kyu-baek commented on backend/src/models/game/socket/services/game.service.ts
> +      newMatch.game_type = gameManager.gameType;
createMatch 는 api 에서 온 요청인거죠?

2023-04-13 06:09 UTC, csstring commented on backend/src/models/game/socket/services/game.service.ts
> +      newMatch.game_type = gameManager.gameType;
createMatch는 경기가 끝나면 시뮬레이터가 호출하는 함수이고 client에서 요청하는 api는 아닙니다

2023-04-13 06:16 UTC, csstring commented on backend/src/models/game/socket/game.gateway.ts
> +  }
gameManager.started == false 이부분은 start가 client 두명이 다 보내는 요청이라 두번째 start요청은 무시하기 위해 넣어 놓은것이고 gameManager && gameManager.playerCount == 2 이부분은 게임 시작할수 있는 상황이 아닌데 인위적으로 start를 하려는 어뷰징 행위 발생시 무시하기 위한 코드 입니다

2023-04-13 07:46 UTC, merged