[Back] chat 엔티티 추가 + dm 중복 생성 수정
3DPong/transcendence pull request #172
Opened 2023-04-22 13:22 UTC by kyu-baek

### 1. 프론트에서 요청하신 type 엔티티 추가
```
export enum MessageType {
  MESSAGE = 'message',
  GAME = 'game',
}
```

### 2. dm이 중복 생성되는 버그 수정

2023-04-22 20:10 UTC, parktest0325 commented
1. 메시지 로그 가져올때 메시지타입이 빠져있고 채널타입이 포함되어있습니다 
2. 채널리스트 가져올때 썸네일이 하나로 고정되어있는거같은데 이건 자세히 확인해봐야될거같네요

2023-04-22 22:35 UTC, JuneParkCode requested changes
일부 수정사항 제안했고, 확인했습니다.

2023-04-22 22:35 UTC, JuneParkCode commented on backend/src/models/chat/api/services/chat.service.ts
>      }
```suggestion
const user: User = dmChannel.first_user_id === first_user.user_id ? dmChannel.second_user : dmChannel.first_user;
const channel: Channel = await this.getChannel(dmChannel.channel_id);
return this.channelResult(channel, dmChannel.first_user);
```

이렇게 깔끔하게 쓰는게 나아보입니당

2023-04-22 22:35 UTC, JuneParkCode commented on backend/src/models/chat/dto/channel.dto.ts
`@IsUrl()` 빠진 이유가 무엇인가요?
만약 에러를 뱉었기 때문이라면, `@IsUrl` 의 옵션에 대해서 조금 찾아보시면, `localhost:8080` 과 같은 케이스까지 허용하려면

```suggestion
@IsUrl({ require_tld: false })
```
 과 같은 옵션을 부여하여 허용할 수 있습니다.

2023-04-22 22:35 UTC, JuneParkCode commented on backend/src/models/chat/entities/messageLog.entity.ts
> +  @Factory((faker) => faker.helpers.arrayElement(['message', 'game']))
이거 Seeding 할 때 오류를 오히려 만들 수 있습니다.
그냥 `message` 형태만 주는 것이 바람직해보입니다.
따로 더미 데이터를 넣고 싶다면, 여기서 말고 적절한 폼의 `content` 와 함께 더미 데이터를 넣는걸 따로 만들어야할듯.

2023-04-24 05:48 UTC, kyu-baek commented on backend/src/models/chat/api/services/chat.service.ts
>      }
반영 했습니다~

2023-04-24 06:27 UTC, kyu-baek commented
1. dm에서 message 를 send 한 뒤에 invite emit을 보낼 때 썸네일이 필요한가? -> dm은 썸네일을 사용하지 않고 오너 프로필을 사용

2023-04-24 06:44 UTC, csstring approved these changes
message type 수정하신 부분 확인했습니다

2023-04-24 07:03 UTC, kyu-baek commented on backend/src/models/chat/dto/channel.dto.ts
반영 했습니다~

2023-04-24 07:03 UTC, kyu-baek commented on backend/src/models/chat/entities/messageLog.entity.ts
> +  @Factory((faker) => faker.helpers.arrayElement(['message', 'game']))
반영 했습니다~

2023-04-24 07:21 UTC, merged